package com.senorpez.projectcars2.racedata;

public enum PacketType {
    PACKET_CAR_PHYSICS,
    PACKET_RACE_DEFINITION,
    PACKET_PARTICIPANTS,
    PACKET_TIMINGS,
    PACKET_GAME_STATE,
    PACKET_WEATHER_STATE,
    PACKET_VEHICLE_NAMES,
    PACKET_TIME_STATE,
    PACKET_PARTICIPANT_VEHICLE_NAMES,
    PACKET_MAX
}
